sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t somoracle/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true somoracle/react-test npm test

after_success:
  - docker build -t somoracle/multi-client ./client
  - docker build -t somoracle/multi-nginx ./nginx
  - docker build -t somoracle/multi-server ./server
  - docker build -t somoracle/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push somoracle/multi-client
  - docker push somoracle/multi-nginx
  - docker push somoracle/multi-server
  - docker push somoracle/multi-worker
 